### ISSUE TITLE
Feature request: allow to select and download multiple items in the container templates storage section

### ISSUE THREAD

**Issue by CodingSpiderFox** [proxmox/pve-kernel#1]
I'd like to be able to select and download multiple items in one batch in this view:

![image](https://user-images.githubusercontent.com/25173078/104818337-4cc6d500-5827-11eb-89c5-312bdb33b921.png)

**Comment by ThomasLamprecht** [comment]
Hi,

GitHub is only used as mirror, please direct issues to one of the places linked in:
https://pve.proxmox.com/pve-docs/pve-admin-guide.html#getting_help

Note, this feature would be GUI and storage related, but not to pve-kernel.
