### ISSUE TITLE
Submodule fails to load  unadvertised object b34f3bcce258a1bf7f100ad3301fc809b33840e9

### ISSUE THREAD

**Issue by Aterfax** [proxmox/pve-kernel#2]
```

test -f "submodules/ubuntu-focal/README" || git submodule update --init submodules/ubuntu-focal
test -f "submodules/zfsonlinux/Makefile" || git submodule update --init --recursive submodules/zfsonlinux
Submodule 'submodules/zfsonlinux' (git://git.proxmox.com/git/zfsonlinux) registered for path 'submodules/zfsonlinux'
Cloning into '/root/proxmox-kernel/pve-kernel/submodules/zfsonlinux'...
error: Server does not allow request for unadvertised object b34f3bcce258a1bf7f100ad3301fc809b33840e9
Fetched in submodule path 'submodules/zfsonlinux', but it did not contain b34f3bcce258a1bf7f100ad3301fc809b33840e9. Direct fetching of that commit failed.
make: *** [Makefile:121: submodule] Error 1
```

**Comment by Aterfax** [comment]
Via: https://github.com/kiler129/relax-intel-rmrr/tree/master/build/proxmox

**Comment by ThomasLamprecht** [comment]
Hi,

GitHub is only used as mirror, please direct issues to one of the places linked in:
https://pve.proxmox.com/pve-docs/pve-admin-guide.html#getting_help

In your case the issue should be solved now, the mirroring of the ZFS submodule was not fully done yet, the referenced object is now available.

You can use the following command executed in the pve-kernel top level directory to fetch all new objects in all submodules
`git submodule foreach git fetch --tags --recurse-submodules`

A new, fresh clone would naturally also work.
