### ISSUE TITLE
Can't compile the pve-kernel-5.4

### ISSUE THREAD

**Issue by fantinodavide** [proxmox/pve-kernel#3]
Since the zfsonlinux repository has been moved, I am not able to compile the kernel.  I tried cloning it from https://git.proxmox.com/ but it is still not working. I really need to compile a patched kernel, please help.

Some of the errors I get:

Can't locate Debian/Debhelper/Sequence/python3.pm in @INC

Unmet build dependencies: abigail-tools dh-python libblkid-dev libelf-dev libpam0g-dev libssl-dev | libssl1.0-dev lsb-release python3-cffi python3-setuptools python3-sphinx python3-all-dev uuid-dev zlib1g-dev

(@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at (eval 13) line 1.

**Comment by Fabian-Gruenbichler** [comment]
Hi,

GitHub is only used as mirror, please direct issues to one of the places linked in:
https://pve.proxmox.com/pve-docs/pve-admin-guide.html#getting_help

you also might want to run `make debian.prepared; apt build-dep .` in order to install build dependencies.
