### ISSUE TITLE
5.11.22-2-pve is breaking LXD 

### ISSUE THREAD

**Issue by wmchris** [proxmox/pve-kernel#5]
see https://github.com/lxc/lxd/issues/9036

5.11.22-2 breaks command execution inside LXD container, maintainer of LXD blames a kernel patch for this, which doesnt contain the bugfixes.

maybe related with https://discuss.linuxcontainers.org/t/lxc-exec-not-working/11654/5 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=990072 ?

**Comment by wmchris** [comment]
5.11.22-5-pve fixes this issue

**Comment by dbroome1978** [comment]
Is 5.11.22-5-pve available yet?

**Comment by wmchris** [comment]
at least in the testing branch.
