### ISSUE TITLE
5.11.22-4 Issue with Broadcom NIC - bnx2x

### ISSUE THREAD

**Issue by thomasklosinsky** [proxmox/pve-kernel#6]
HP ProLiant BL460c Gen8 with 534FLB or 530FLB Flex10 NIC Adapters (which are those from Broadcom needing the bnx2x drivers)
Other Network adapter like 554FLB (which are those from QLogic) are working.

Kernel Version Linux 5.11.22-4-pve #1 SMP PVE 5.11.22-8
is not working.

Kernel Version Linux 5.11.22-1-pve #1 SMP PVE 5.11.22-2
is working.

**Comment by thomasklosinsky** [comment]
syslog is full of 
bnx2x: probe of (hwaddr) failed with error -22

**Comment by thomasklosinsky** [comment]
Adding tests with different Kernel Versions:
5.11.22-1-pve - working
5.11.22-2-pve - working (no errors)
5.11.22-3-pve - not working (same error)
5.11.22-4-pve - not working (same error)

**Comment by ThomasLamprecht** [comment]
You may be affected by a regression regarding (wrong) detection of SR-IOV, see https://bugzilla.proxmox.com/show_bug.cgi?id=3558#c5

Also note that this is a read-only repo mirror, see the docs for the official channels to get help/report issues: https://pve.proxmox.com/pve-docs/pve-admin-guide.html#getting_help
